# Stage 1: Build stage with secret to download the model
FROM mcr.microsoft.com/devcontainers/python:3.12

#WORKDIR /app

# Create and activate a virtual environment
RUN pip install --upgrade pip
RUN pip install huggingface-hub>=0.17.1

#RUN huggingface-cli download microsoft/Phi-3-mini-4k-instruct-gguf Phi-3-mini-4k-instruct-q4.gguf --local-dir .

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the rest of the application
#COPY . /app

# Expose the port the app runs on
#EXPOSE 5000

# Define the command to run the app
#CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]